### ISSUE TITLE
What should have been the null-byte (string termination) is actually encoded as space (32dec)

### ISSUE THREAD

**Issue by MathiasCiarlo** [gardir/Bitify#1]
./bitify "" => 00100000

**Comment by MathiasCiarlo** [comment]
./bitify "" => 00100000

**Comment by gardir** [comment]
It is not actually the null-terminator that is written, but an argument separator. I will implement a last-argument-check tomorrow ;) this should resolve the issue.
Well sporter though!

**Comment by gardir** [comment]
spotted*, darn auto correct!

**Comment by gardir** [comment]
Latest commit has fixed this isseue.
